models:
  - type: main
    engine: openai
    model: openai/gpt-oss-120b
    api_key_env_var: GROQ_API_KEY
    parameters:
      base_url: https://api.groq.com/openai/v1
      include_reasoning: false
      reasoning_effort: low

colang_version: "1.0"
passthrough: true

instructions:
  - type: general
    content: |
      You are an eCommerce AI Assistant.

rails:
  input:
    flows:
      - jailbreak check
      - pii check
      - toxicity check
      - prompt injection check
      - html script check
      - intent misalignment check
      - self check input
